name: Python CI

on:
  push:
    branches:
      - '**'         # Run on pushes to all branches
  pull_request:
    branches:
      - '**'         # Run on PRs for any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: exists('requirements.txt')
        run: |
          pip install -r requirements.txt

      - name: Run all Python scripts
        run: |
          echo "Running all Python scripts..."
          for file in $(find . -name "*.py"); do
            echo "Executing $file"
            python "$file"
          done
